module Storage
  # Interface implemented by every storage backend.
  #
  # Keys are generated by the application (see .generate_key), never taken
  # from clients, and a backend validates them before deriving a filesystem
  # path or object name from them. Data is always a binary String.
  class Backend
    KEY_FORMAT = /\A\h{8}-\h{4}-\h{4}-\h{4}-\h{12}\z/

    def self.generate_key
      SecureRandom.uuid
    end

    # Builds an instance from this backend's section of the settings.
    def self.from_settings(settings)
      raise NotImplementedError, "#{self} must implement .from_settings"
    end

    # Short name recorded in Blob#storage_backend, e.g. "local".
    def name
      raise NotImplementedError, "#{self.class} must implement #name"
    end

    # Stores +data+ under +key+. Raises Storage::Error when it cannot.
    def write(key, data)
      raise NotImplementedError, "#{self.class} must implement #write"
    end

    # Returns the bytes stored under +key+. Raises Storage::NotFound when the
    # key is absent and Storage::Error on any other failure.
    def read(key)
      raise NotImplementedError, "#{self.class} must implement #read"
    end

    # Removes the object under +key+; an absent key is not an error.
    def delete(key)
      raise NotImplementedError, "#{self.class} must implement #delete"
    end

    private

    def validate_key!(key)
      raise ArgumentError, "invalid storage key #{key.inspect}" unless KEY_FORMAT.match?(key.to_s)

      key
    end
  end
end
